In [2]:
import numpy as np


# Word-level one-hot encoding

In [17]:
samples = ['The cat sat on the mat.', 'The dog ate my homework.']
token_index = {}
for sample in samples:
    print(sample)
    for word in sample.split():
        print(word)
        if word not in token_index:
            token_index[word] = len(token_index) + 1
    print(token_index)
# print('token_index:', token_index)
print("*"*50)
max_length = 10
results = np.zeros(shape=(len(samples), max_length, max(token_index.values()) + 1))
print("results befor one hot encoding: \n",results)
print(results)
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1.
print("*"*50)
print('results after one hot encoding: \n',results)

The cat sat on the mat.
The
cat
sat
on
the
mat.
{'The': 1, 'cat': 2, 'sat': 3, 'on': 4, 'the': 5, 'mat.': 6}
The dog ate my homework.
The
dog
ate
my
homework.
{'The': 1, 'cat': 2, 'sat': 3, 'on': 4, 'the': 5, 'mat.': 6, 'dog': 7, 'ate': 8, 'my': 9, 'homework.': 10}
**************************************************
results befor one hot encoding: 
 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 

# Using Keras for word-level one-hot encoding

In [19]:
from keras.preprocessing.text import Tokenizer

In [32]:
samples = ['The cat sat on the mat.', 'The dog ate my homework.']
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)

print("sequences: ",sequences)
one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary')
print('one_hot_results: ')
print(one_hot_results)
word_index = tokenizer.word_index
print("word_index: ",word_index)
print('Found %s unique tokens.' % len(word_index))

sequences:  [[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]
one_hot_results: 
[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
word_index:  {'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat': 5, 'dog': 6, 'ate': 7, 'my': 8, 'homework': 9}
Found 9 unique tokens.


# Word embeddings

In [41]:
from keras.layers import Embedding
from keras.datasets import imdb
from tensorflow.keras import preprocessing
from keras.models import Sequential
from keras.layers import Flatten, Dense

In [42]:
# embedding_layer = Embedding(1000, 64)

In [44]:

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words = 10000)
x_train = preprocessing.sequence.pad_sequences(x_train, maxlen=20)
x_test = preprocessing.sequence.pad_sequences(x_test, maxlen=20)


model = Sequential()
model.add(Embedding(10000, 8, input_length=20))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
model.summary()


2023-10-15 22:00:44.895778: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-10-15 22:00:44.896644: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-10-15 22:00:44.897161: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (onstak-Inspiron-14-5410): /proc/driver/nvidia/version does not exist
2023-10-15 22:00:44.906886: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 8)             80000     
                                                                 
 flatten (Flatten)           (None, 160)               0         
                                                                 
 dense (Dense)               (None, 1)                 161       
                                                                 
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________


In [45]:
history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
625/625 [==============================] - 2s 2ms/step - loss: 0.6727 - acc: 0.6133 - val_loss: 0.6302 - val_acc: 0.6832
Epoch 2/10
625/625 [==============================] - 1s 1ms/step - loss: 0.5564 - acc: 0.7401 - val_loss: 0.5367 - val_acc: 0.7274
Epoch 3/10
625/625 [==============================] - 1s 1ms/step - loss: 0.4731 - acc: 0.7797 - val_loss: 0.5052 - val_acc: 0.7442
Epoch 4/10
625/625 [==============================] - 1s 2ms/step - loss: 0.4303 - acc: 0.8066 - val_loss: 0.4952 - val_acc: 0.7514
Epoch 5/10
625/625 [==============================] - 1s 1ms/step - loss: 0.4013 - acc: 0.8196 - val_loss: 0.4934 - val_acc: 0.7524
Epoch 6/10
625/625 [==============================] - 1s 1ms/step - loss: 0.3784 - acc: 0.8331 - val_loss: 0.4942 - val_acc: 0.7538
Epoch 7/10
625/625 [==============================] - 1s 1ms/step - loss: 0.3577 - acc: 0.8435 - val_loss: 0.4966 - val_acc: 0.7550
Epoch 8/10
625/625 [==============================] - 1s 1ms/step - loss: 0.